version: "3.9"
services:

  server:
    build: ./server
    ports:
      - 4000:4000
    command: "npm run dev"

    environment:
      - NODE_ENV=dev 
      - CLEAR_REDIS_ON_DEV_START=false
      - SEQUELIZE_CONN_URI=sqlite://lr.db
      - REDIS_URI=redis://redis:6380
      - SESSION_SECRET=2f3lkqjhl2fjk2h2f2lkfj3hflkj2hl
    volumes:
      - ./server/src:/home/node/server/src

  client:
    build: ./client
    ports:
      - 3000:3000
    command: "npm run dev"
    volumes:
      - ./client/src:/home/node/client/src


  redis:
    image: redis:7.0.0-alpine
    ports:
      - 6380:6380